<a href="https://colab.research.google.com/github/DeepuJose24/DJKeekarikattu/blob/main/Python%20Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from numpy.core.numeric import array_equal
# load a matrix
import numpy as np


np.array[1,2,3]
  

TypeError: ignored

In [24]:
# load a matrix
import numpy as np
arr= np.array ([1,2,3])
A= np.array([1,2,3,4])
B=np.array([[1],[2],[3],[4]])
matrix=np.array([[1,2,3],[3,4,5],[4,4,6]])
print(matrix)
from scipy import sparse
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

vector=np.array([1,2,3,4,5,6])
vector[3]
vector[5]

vector[1]
matrix[1,1]

[[1 2 3]
 [3 4 5]
 [4 4 6]]
  (0, 0)	1
  (0, 1)	2
  (0, 2)	3
  (1, 0)	3
  (1, 1)	4
  (1, 2)	5
  (2, 0)	4
  (2, 1)	4
  (2, 2)	6


4

In [29]:
import numpy as np
matrix= np.array([[1,2,3], [4,0,8],[3,8,6]])
print(matrix)
matrix[2,0]

[[1 2 3]
 [4 0 8]
 [3 8 6]]


3

In [36]:
import numpy as np
vector= np.array([1,2,3,4,5,6])
vector[3:]
vector[-1]
matrix=np.array([[1,0,4,5],[2,3,5,1],[5,0,0,3],[4,5,6,1]])
print(matrix)
matrix[:2,:]

[[1 0 4 5]
 [2 3 5 1]
 [5 0 0 3]
 [4 5 6 1]]


array([[1, 0, 4, 5],
       [2, 3, 5, 1]])