<a href="https://colab.research.google.com/github/DeepuJose24/DJKeekarikattu/blob/main/Python_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy.core.numeric import array_equal
# load a matrix
import numpy as np


np.array[1,2,3]
  

TypeError: ignored

In [ ]:
# load a matrix
import numpy as np
arr= np.array ([1,2,3])
A= np.array([1,2,3,4])
B=np.array([[1],[2],[3],[4]])
matrix=np.array([[1,2,3],[3,4,5],[4,4,6]])
print(matrix)
from scipy import sparse
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

vector=np.array([1,2,3,4,5,6])
vector[3]
vector[5]

vector[1]
matrix[1,1]

[[1 2 3]
 [3 4 5]
 [4 4 6]]
  (0, 0)	1
  (0, 1)	2
  (0, 2)	3
  (1, 0)	3
  (1, 1)	4
  (1, 2)	5
  (2, 0)	4
  (2, 1)	4
  (2, 2)	6


4

In [ ]:
import numpy as np
matrix= np.array([[1,2,3], [4,0,8],[3,8,6]])
print(matrix)
matrix[2,0]

[[1 2 3]
 [4 0 8]
 [3 8 6]]


3

In [ ]:
import numpy as np
vector= np.array([1,2,3,4,5,6])
vector[3:]
vector[-1]
matrix=np.array([[1,0,4,5],[2,3,5,1],[5,0,0,3],[4,5,6,1]])
print(matrix)
matrix[:2,:3]
matrix[:,0:2]

[[1 0 4 5]
 [2 3 5 1]
 [5 0 0 3]
 [4 5 6 1]]


array([[1, 0],
       [2, 3],
       [5, 0],
       [4, 5]])

In [ ]:
from numpy.lib.function_base import vectorize
import numpy as np
vectorize
matrix=np.array([[1,2],[0,0],[3,5],[4,0]])
matrix[1:,:0]
matrix.shape
matrix.ndim
matrix.size
add_100=lambda i:i+100
vectorized_add_100=np.vectorize(add_100)
vectorized_add_100(matrix)

array([[101, 102],
       [100, 100],
       [103, 105],
       [104, 100]])

In [ ]:
import numpy as np
matrix=np.array([[1,1],[2,3],[6,5]])
matrix+100
np.max(matrix,axis=0)
np.std(matrix)
np.mean(matrix, axis=1)
       

array([1. , 2.5, 5.5])

In [ ]:
import numpy as np
vector_a=np.array([1,2,4,5])
vector_b=np.array([3,6,7,8])
np.dot(vector_a,vector_b)
matrix=np.array([[1,2,4,5],[3,4,5,6],[3,0,9,0]])
matrix.reshape(1,-1)
matrix.T

array([[1, 3, 3],
       [2, 4, 0],
       [4, 5, 9],
       [5, 6, 0]])

In [ ]:
import numpy as np
np.array([[1,2,3,4,5]]).T
matrix=np.array([[1,2,3],[4,5,6],[6,5,6]])
matrix.flatten()
np.linalg.matrix_rank(matrix)
np.linalg.det(matrix)
matrix.diagonal(offset=-1)
matrix.trace()
sum(matrix.diagonal())

12

In [6]:
import numpy as np
matrix=np.array([[1,-1,3],[1,1,6],[3,8,9]])
eigenvalues=np.linalg.eig(matrix)
eigenvalues


(array([13.55075847,  0.74003145, -3.29078992]),
 array([[-0.17622017, -0.96677403, -0.53373322],
        [-0.435951  ,  0.2053623 , -0.64324848],
        [-0.88254925,  0.15223105,  0.54896288]]))

In [ ]:
import numpy as np
linalg.eig

matrix=np.array([[1,2,3],[2,4,5]])
eigenvalues,eigenvectors=np.linalg.eig(matrix)
eigenvalues

NameError: ignored

In [21]:
import numpy as np

arr1= np.array([1,2,3,4], ndmin=3)
print(arr1)
arr2=np.array([1,2,3,4])
print (arr1, arr[0],arr2[0][1],arr3[0][1][2])




[[[1 2 3 4]]]


IndexError: ignored

In [22]:
import numpy as np
arr1=np.array(['apple','banana','grapes'])
print(arr1.dtype)

<U6


In [24]:
import numpy as np
arr2=np.array([1,2,3,4],dtype='i')
print(arr2)
print(arr2.dtype)

[1 2 3 4]
int32


In [28]:
import numpy as np
arr3=np.array([3.47,2.14,4.32])
newarr=arr3.astype('i')
print(newarr)
print(newarr.dtype)

arr4=np.array([1,2,3,4])
x=arr4.copy()
arr4[0]=42
print(arr4)
print(x)

[3 2 4]
int32
[42  2  3  4]
[1 2 3 4]


In [30]:
import numpy as np
arr1=np.array([1,2,3,4,5])
x=arr1.view()
arr1[1]=-15
print(arr1)
print(x)
x[0]=10
print(arr1)

[  1 -15   3   4   5]
[  1 -15   3   4   5]
[ 10 -15   3   4   5]


In [36]:
import numpy as np
arr=np.array([1,2,3,4,5,6,6,7,8,9,11])
newarr=arr.reshape(1,3,2)
print(newarr)

ValueError: ignored

In [37]:
import numpy as np
arr=np.array([1,2,3])
for x in arr:
  print(x)


1
2
3


In [41]:
import numpy as np
arr=np.array([[1,2,3],[2,3,4],[3,4,5],[1,1,9]])
for x in arr:
  print(x)
  for x in arr:
    for y in x:
      print(y)
      for x in arr:
        for y in x:
          for z in y:
            print(z)


[1 2 3]
1


TypeError: ignored

In [47]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([3,4,5])
arr=np.concatenate((arr1, arr2))
print(arr)

[1 2 3 3 4 5]


In [50]:
import numpy as np
arr1=np.array([[1,2],[3,5]])
arr2=np.array([[4,3],[5,6]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2]
 [3 5]
 [4 3]
 [5 6]]


In [51]:
import numpy as np
arr1=np.array([1,2])
arr2=np.array([3,4])
arr=np.stack((arr1,arr2),axis=1)
print(arr)
print(arr.shape)

[[1 3]
 [2 4]]
(2, 2)


In [52]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 3 4 5 6]


In [53]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([1,4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3 4]
 [1 4 5 6]]


In [56]:
import numpy as np
arr1=([1,2,3,3,5,6,3])
x=np.where(arr1==3)
print(x)
x=np.where(arr%2==1)
print(x)

(array([], dtype=int64),)
(array([0, 0, 1, 1]), array([0, 2, 0, 2]))


In [57]:
import numpy as np
arr=np.array([1,6,7,2,4])
print(np.sort(arr))

[1 2 4 6 7]


In [60]:
import numpy as np
arr1=([[9,2,3],[4,3,1]])
print(np.sort(arr1))

[[2 3 9]
 [1 3 4]]


In [61]:
import numpy as np
arr1=(['apple','pistachio', 'cutlets'])
print(np.sort(arr1))

['apple' 'cutlets' 'pistachio']


In [68]:
import numpy as np
from numpy import random

x=random.randint(100, size=(3,5))
print(x)
x1=random.rand(3,5)
print(x1)

[[58 28 73 22 36]
 [25 11 54 69 13]
 [ 1 71 69 65 32]]
[[0.80331503 0.771814   0.57747069 0.8265592  0.0552833 ]
 [0.01328166 0.14936332 0.67778327 0.65739001 0.0457155 ]
 [0.15046783 0.6330334  0.54966527 0.24550294 0.93328706]]


In [71]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[9,7,0]])
b=np.array([[3,2,4],[4,7,8],[4,3,2]])
print(a+2)
print(b*2)
print(a/2)
c=a+b
print(c)
d=a-b
print(d)
e=a*b
print(e)

[[ 3  4  5]
 [ 6  7  8]
 [11  9  2]]
[[ 6  4  8]
 [ 8 14 16]
 [ 8  6  4]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [4.5 3.5 0. ]]
[[ 4  4  7]
 [ 8 12 14]
 [13 10  2]]
[[-2  0 -1]
 [ 0 -2 -2]
 [ 5  4 -2]]
[[ 3  4 12]
 [16 35 48]
 [36 21  0]]


In [73]:
import numpy as np
a=np.array([[3,2,1],[4,6,8],[1,2,3]])
print(a)
ta=np.transpose(a)
print(ta)

[[3 2 1]
 [4 6 8]
 [1 2 3]]
[[3 4 1]
 [2 6 2]
 [1 8 3]]


In [76]:
import numpy as np
a=np.arange(5,50,2)
print(a)
print('Mean:',np.mean(a))
print('Standard deviation:',np.std(a))
print('Median:',np.median(a))

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
Mean: 27.0
Standard deviation: 13.2664991614216
Median: 27.0


In [79]:
import numpy as np
a=np.array([[1,3,5],[45,76,90],[23,1,0]])
print(a)
print('Max:', np.max(a, axis=0))
print('Min:',np.min(a,axis=1))

[[ 1  3  5]
 [45 76 90]
 [23  1  0]]
Max: [45 76 90]
Min: [ 1 45  0]
